<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0lrivQ3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0lrivQ3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0lrivQ3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0lrivQ3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0lrivQ3\App_KernelDevDebugContainer([
    'container.build_hash' => '0lrivQ3',
    'container.build_id' => 'b78602ee',
    'container.build_time' => 1592903477,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0lrivQ3');
