<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTO6xPjS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTO6xPjS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTO6xPjS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTO6xPjS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTO6xPjS\App_KernelDevDebugContainer([
    'container.build_hash' => 'TO6xPjS',
    'container.build_id' => '00cc56cc',
    'container.build_time' => 1590344708,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTO6xPjS');
