<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1VmWV3w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1VmWV3w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1VmWV3w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1VmWV3w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1VmWV3w\App_KernelDevDebugContainer([
    'container.build_hash' => '1VmWV3w',
    'container.build_id' => '70056b12',
    'container.build_time' => 1587214336,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1VmWV3w');
